nodeLinker: pnp

# yarn pre|post는 종속성 트리가 변경된 후에만 호출 (https://yarnpkg.com/advanced/lifecycle-scripts)
# 이로 인해 의도한대로 pre|post를 사용할 수가 없음
# 
# 종속성 트리와 관련없이 script 후에 반드시 호출하도록 plugin 설치
# https://github.com/mhassan1/yarn-plugin-after-install
afterInstall: yarn postinstall
plugins:
  - checksum: 0a2a35fbed2f33f0df1ceb1db51bf72554201f994eaecb86cbc62a295c3d05f7cc44fa8be8e64fc5e1c0bee4f529a17a0cc429ea9e3486ad467443291d5a8e3b
    path: .yarn/plugins/@yarnpkg/plugin-after-install.cjs
    spec: "https://raw.githubusercontent.com/mhassan1/yarn-plugin-after-install/v0.6.0/bundles/@yarnpkg/plugin-after-install.js"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
