#!/usr/bin/env sh

# branch="$(git rev-parse --abbrev-ref HEAD)"
# echo "branch $branch"

# if [ "$branch" = "main" ]; then
#   echo "Can't commit to 'main' branch"
#   exit 1
# fi

. "$(dirname -- "$0")/_/husky.sh"

yarn pre-commit